name: Sync Repos

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repo
      uses: actions/checkout@v2
      with:
        repository: <source-repo-owner>/<source-repo-name>
        token: ${{ secrets.SOURCE_REPO_TOKEN }}

    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: <private-repo-owner>/<private-repo-name>
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        path: ./private-repo

    - name: Sync changes
      run: |
        cd ./private-repo
        git config user.name "GitHub Actions"
        git config user.email "<your-email@example.com>"
        
        # Fetch and merge changes from source repo
        git fetch origin
        git merge origin/main --no-ff --no-commit
        
        # Push changes to private repo
        git push origin main
