name: Sync with Remote Repository

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"

    - name: Fetch latest changes from remote
      run: git fetch origin

    - name: Check for new commits
      id: check_commits
      run: |
        latest_hash=$(git rev-parse HEAD)
        remote_hash=$(git rev-parse origin/main)
        if [ "$latest_hash" != "$remote_hash" ]; then
          echo "New commit detected"
          git pull origin main
          git push origin main
        else
          echo "No new commits"
        fi
