name: Testing

on:
  push:
    branches:
      - develop
    paths:
      - '**'

jobs:
  sync_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repo
      uses: actions/checkout@v3
      with:
        repository: Rohail07/Rohailtest
        path: https://github.com/Australian-Associated-Press/Rohailtest/tree/develop
        ref: develop

    - name: Checkout remote repo
      uses: actions/checkout@v3
      with:
        repository: rohail3107/rohail3107.github.io
        path: https://github.com/rohail3107/rohail3107.github.io/tree/master
        ref: master

    - name: Compare commits
      run: |
        cd remote-repo
        REMOTE_COMMIT=$(git rev-parse HEAD)
        cd ../private-repo
        PRIVATE_COMMIT=$(git rev-parse HEAD)
        echo "Remote commit: $REMOTE_COMMIT"
        echo "Private commit: $PRIVATE_COMMIT"
        if [ "$REMOTE_COMMIT" != "$PRIVATE_COMMIT" ]; then
          echo "Private repository is out-of-date with the remote repository."
          # If there are changes, perform the sync
          cd ../private-repo
          git pull origin master
          git pull ../remote-repo master
          git push origin develop
          echo "Private repository has been updated with changes from the remote repository."
        else
          echo "Private repository is up-to-date with the remote repository."
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT}}
